require('dotenv').config();

const {
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  NODE_ENV,
  PRODUCTION_URL,
  UNSPLASH_ACCESS_KEY,
  UNSPLASH_SECRET_KEY,
} = process.env;

module.exports = {
  env: {
    ENV: NODE_ENV,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    PRODUCTION_URL,
    UNSPLASH_ACCESS_KEY,
    UNSPLASH_SECRET_KEY,
  },
};
